pipeline {
  agent {
    docker { image 'node:18-alpine' }
    
  }
  agent{
    docker {image 'redis'}
  }
  
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        sh 'redis --version'
      }
    }
  }
}
