pipeline {
  // agent {
  //   docker { image 'node:18-alpine' }
    
  // }
  agent{
    docker {image 'pavanshekar/aws_nod_application:aws_nod_application'}
  }
  
  stages {
    stage('Test') {
      steps {
       // sh 'node --version'
        sh 'docker run pavanshekar/aws_nod_application:aws_nod_application'
      }
    }
  }
}
